version: "3.7"

services:
  app:
    build:
      args:
        user: azimsport
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: azimsport-app
    container_name: azimsport-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "8222:8022"
    networks:
      - azimsport-bridge

networks:
  azimsport-bridge:
    external: true
